//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS
    {
        public string C_ID { get; set; }
        public string C_DIVISION { get; set; }
        public int C_CMTID { get; set; }
        public string C_TEACHER { get; set; }
        public short C_YEAR { get; set; }
        public string C_ENTRYUSER { get; set; }
        public System.DateTime C_ENTRYDATE { get; set; }
    }
}
