//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT
    {
        public long D_ID { get; set; }
        public string D_FILE { get; set; }
        public string D_FOR { get; set; }
        public string D_REFID { get; set; }
        public string D_ENTRYUSER { get; set; }
        public System.DateTime D_ENTRYDATE { get; set; }
        public int D_SIZE { get; set; }
        public string D_EXT { get; set; }
    }
}
