//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_DETAILS
    {
        public string ED_ID { get; set; }
        public string ED_INITIAL { get; set; }
        public string ED_NAMEF { get; set; }
        public string ED_NAMEM { get; set; }
        public string ED_NAMEL { get; set; }
        public string ED_MOBILE { get; set; }
        public string ED_SEX { get; set; }
        public string ED_DESIGNATION { get; set; }
        public System.DateTime ED_JOINDATE { get; set; }
        public Nullable<System.DateTime> ED_BIRTHDATE { get; set; }
        public string ED_EMAILID { get; set; }
        public string ED_ENTRYUSER { get; set; }
        public System.DateTime ED_ENTRYDATE { get; set; }
        public string ED_ACTIVE { get; set; }
        public bool ED_TEACHER { get; set; }
    }
}
