//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_MST
    {
        public string SM_ID { get; set; }
        public string SM_INITIAL { get; set; }
        public string SM_NAMEF { get; set; }
        public string SM_NAMEM { get; set; }
        public string SM_NAMEL { get; set; }
        public string SM_MOBILE { get; set; }
        public string SM_SEX { get; set; }
        public System.DateTime SM_REGSDATE { get; set; }
        public Nullable<System.DateTime> SM_BIRTHDATE { get; set; }
        public string SM_EMAILID { get; set; }
        public string SM_EMAILIDP { get; set; }
        public string SM_ENTRYUSER { get; set; }
        public System.DateTime SM_ENTRYDATE { get; set; }
        public string SM_ACTIVE { get; set; }
    }
}
